# Generated by Django 3.1.3 on 2020-11-25 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Название')),
                ('slug', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('measure', models.CharField(choices=[('250 ml', '250 ml'), ('500 ml', '500 ml'), ('700 ml', '700 ml')], default='500mg', max_length=255, verbose_name='Мера')),
            ],
            options={
                'verbose_name': 'Кофе',
                'verbose_name_plural': 'Список кофе',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderCoffee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('city', models.CharField(choices=[('Kzo', 'Kyzylorda')], default='Kzo', max_length=255, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Заказчик кофе',
                'verbose_name_plural': 'Заказчики кофе',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderCoffeeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('paid', models.BooleanField(blank=True, default=False, null=True, verbose_name='Оплата')),
                ('coffee', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coffee', to='coffee_web.coffee', verbose_name='Кофе')),
                ('order', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_coffee', to='coffee_web.ordercoffee', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Лист заказов',
                'verbose_name_plural': ' Листы заказов',
                'ordering': ['-created'],
            },
        ),
    ]
